version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: codecollab_ryan
      POSTGRES_PASSWORD: secure123
      POSTGRES_DB: codecollab_db
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: